import { Artwork } from './supabase';

export const mockArtworks: Artwork[] = [
  {
    id: '1',
    qr_code: 'ART001',
    title_fr: 'Masque Dogon',
    title_en: 'Dogon Mask',
    title_wo: 'Masque Dogon',
    description_fr: 'Ce masque cérémoniel Dogon du Mali représente un esprit ancestral. Utilisé lors de rituels sacrés, il symbolise la connexion entre le monde des vivants et celui des ancêtres. Les Dogons sont réputés pour leurs connaissances astronomiques avancées et leur riche cosmogonie.',
    description_en: 'This ceremonial Dogon mask from Mali represents an ancestral spirit. Used in sacred rituals, it symbolizes the connection between the world of the living and that of the ancestors. The Dogon are renowned for their advanced astronomical knowledge and rich cosmogony.',
    description_wo: 'Masque cérémoniel Dogon bu Mali, dafa mel esprit ancestral. Utilisé ci rituels sacrés, symbolise connexion entre monde bu vivants ak ancestors. Dogon yi dañu gëna ci xam-xam bu astronomie ak cosmogonie bu nit.',
    historical_context_fr: 'Les Dogons du Mali possèdent une culture millénaire fascinante. Leurs masques jouent un rôle central dans les cérémonies funéraires et les festivals agraires. La danse des masques, appelée "Dama", peut durer plusieurs jours et mobilise toute la communauté.',
    historical_context_en: 'The Dogon of Mali possess a fascinating thousand-year-old culture. Their masks play a central role in funeral ceremonies and agricultural festivals. The mask dance, called "Dama", can last several days and mobilizes the entire community.',
    historical_context_wo: 'Dogon yi ci Mali amna culture bu millénaire bu fascinant. Masques yi jouer rôle central ci cérémonies funéraires ak festivals agraires. Danse bu masques, "Dama", mën na dure plusieurs jours te mobilise communauté lépp.',
    image_url: 'https://thumbs.dreamstime.com/b/masque-de-dogon-7253396.jpg',
    audio_fr_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    audio_en_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    audio_wo_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    pdf_url: 'https://www.africau.edu/images/default/sample.pdf',
    period: '13ème-15ème siècle',
    origin: 'Mali, Pays Dogon',
    materials: 'Bois, pigments naturels',
    artist: 'Artisan Dogon',
    created_at: new Date().toISOString()
  },
  {
    id: '2',
    qr_code: 'ART002',
    title_fr: 'Statue Fang',
    title_en: 'Fang Statue',
    title_wo: 'Statue Fang',
    description_fr: 'Sculpture ancestrale du peuple Fang du Gabon. Cette statue gardienne protégeait les reliques familiales. Elle incarne la force spirituelle et le lien avec les ancêtres. Le style Fang se caractérise par ses formes géométriques épurées et son expression puissante.',
    description_en: 'Ancestral sculpture of the Fang people from Gabon. This guardian statue protected family relics. It embodies spiritual strength and connection with ancestors. The Fang style is characterized by its refined geometric forms and powerful expression.',
    description_wo: 'Sculpture ancestral bu Fang ci Gabon. Statue bi gardien dafa protéger reliques bu famille. Mel spiritual strength ak lien ak ancestors. Style Fang caracterisé par formes géométriques bu épuré ak expression bu puissant.',
    historical_context_fr: 'Les Fang sont un peuple d\'Afrique centrale présent au Gabon, Cameroun et Guinée équatoriale. Leurs sculptures de reliquaires, appelées "Bieri", sont parmi les plus célèbres de l\'art africain. Ces œuvres ont inspiré de nombreux artistes européens du 20ème siècle.',
    historical_context_en: 'The Fang are a Central African people present in Gabon, Cameroon and Equatorial Guinea. Their reliquary sculptures, called "Bieri", are among the most famous in African art. These works inspired many 20th century European artists.',
    historical_context_wo: 'Fang yi nekk ci peuple bu Afrique centrale ci Gabon, Cameroun ak Guinée équatoriale. Sculptures bu reliquaires, "Bieri", nekk ci œuvres bu gëna famous ci art africain. Œuvres yii inspiré artistes européens bu 20ème siècle.',
    image_url: 'https://tse3.mm.bing.net/th/id/OIP._csDZ96vLN8_jDfk9epGCAHaLH?cb=12&rs=1&pid=ImgDetMain&o=7&rm=3',
    audio_fr_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    audio_en_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    audio_wo_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    pdf_url: 'https://www.africau.edu/images/default/sample.pdf',
    period: '18ème-19ème siècle',
    origin: 'Gabon, Cameroun',
    materials: 'Bois d\'okoumé, laiton',
    artist: 'Sculpteur Fang',
    created_at: new Date().toISOString()
  },
  {
    id: '3',
    qr_code: 'ART003',
    title_fr: 'Couronne Yoruba',
    title_en: 'Yoruba Crown',
    title_wo: 'Couronne Yoruba',
    description_fr: 'Couronne royale yoruba ornée de perles. Portée par les Oba (rois), elle représente le pouvoir divin et l\'autorité spirituelle. Les perles symbolisent la richesse et la sagesse. Chaque élément iconographique raconte l\'histoire du royaume.',
    description_en: 'Royal Yoruba crown adorned with beads. Worn by Obas (kings), it represents divine power and spiritual authority. The beads symbolize wealth and wisdom. Each iconographic element tells the story of the kingdom.',
    description_wo: 'Couronne royal Yoruba bu ornée perles. Portée par Oba (rois), représente pouvoir divin ak autorité spirituelle. Perles yi symbolisent richesse ak sagesse. Chaque élément iconographique raconte histoire bu royaume.',
    historical_context_fr: 'Les Yoruba du Nigeria possèdent l\'une des monarchies les plus anciennes d\'Afrique. Les couronnes perlées, appelées "Ade", sont des symboles sacrés du pouvoir royal. Seuls les Oba ont le droit de porter ces couronnes lors des cérémonies importantes.',
    historical_context_en: 'The Yoruba of Nigeria possess one of the oldest monarchies in Africa. Beaded crowns, called "Ade", are sacred symbols of royal power. Only Obas have the right to wear these crowns during important ceremonies.',
    historical_context_wo: 'Yoruba yi ci Nigeria amna monarchies yu gëna ancien ci Afrique. Couronnes perlées, "Ade", nekk symboles sacrés bu pouvoir royal. Oba rek la amna droit bu porter couronnes yii ci cérémonies importantes.',
    image_url: 'https://tse1.mm.bing.net/th/id/OIP.43eGZTFt-l6Y6reTHuSdHAHaLH?cb=12&rs=1&pid=ImgDetMain&o=7&rm=3',
    audio_fr_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    audio_en_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    audio_wo_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    pdf_url: 'https://www.africau.edu/images/default/sample.pdf',
    period: '19ème siècle',
    origin: 'Nigeria, Royaume Yoruba',
    materials: 'Perles, tissu, cuir',
    artist: 'Artisan Royal Yoruba',
    created_at: new Date().toISOString()
  },
  {
    id: '4',
    qr_code: 'ART010',
    title_fr: 'Bronze du Bénin',
    title_en: 'Benin Bronze',
    title_wo: 'Bronze Bénin',
    description_fr: 'Plaque en bronze du royaume du Bénin. Ces œuvres d\'art ornaient le palais royal et racontaient l\'histoire des rois. La technique de fonte à la cire perdue témoigne d\'un savoir-faire exceptionnel. Ces bronzes sont parmi les chefs-d\'œuvre de l\'art africain.',
    description_en: 'Bronze plaque from the Kingdom of Benin. These artworks adorned the royal palace and told the history of kings. The lost-wax casting technique demonstrates exceptional craftsmanship. These bronzes are among the masterpieces of African art.',
    description_wo: 'Plaque bronze bu royaume Bénin. Œuvres d\'art yi ornaient palais royal te racontaient histoire bu rois. Technique bu fonte à cire perdue témoigne savoir-faire exceptionnel. Bronzes yi nekk ci chefs-d\'œuvre bu art africain.',
    historical_context_fr: 'Le royaume du Bénin (actuel Nigeria) était un état puissant du 13ème au 19ème siècle. Les bronzes du Bénin, créés par la guilde des forgerons, sont considérés comme l\'un des plus grands trésors artistiques d\'Afrique. Ils ont été pillés en 1897 lors de l\'expédition britannique.',
    historical_context_en: 'The Kingdom of Benin (present-day Nigeria) was a powerful state from the 13th to 19th century. Benin bronzes, created by the blacksmiths\' guild, are considered one of Africa\'s greatest artistic treasures. They were looted in 1897 during the British expedition.',
    historical_context_wo: 'Royaume bu Bénin (Nigeria bu léegi) nekk état puissant ci 13ème jusque 19ème siècle. Bronzes bu Bénin, créés par guilde bu forgerons, considérés comme trésors artistiques bu gëna important ci Afrique. Dañuy looted ci 1897 ci expédition britannique.',
    image_url: 'https://s3-ap-southeast-1.amazonaws.com/gounesco.com/wp-content/uploads/2018/02/21213004/Obas-Head-Bronze.jpg',
    audio_fr_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    audio_en_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    audio_wo_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    pdf_url: 'https://www.africau.edu/images/default/sample.pdf',
    period: '16ème-17ème siècle',
    origin: 'Nigeria, Royaume du Bénin',
    materials: 'Bronze, cuivre',
    artist: 'Guilde des Forgerons du Bénin',
    created_at: new Date().toISOString()
  },
  {
    id: '5',
    qr_code: 'ART012',
    title_fr: 'Poids à Peser l\'Or Akan',
    title_en: 'Akan Gold Weight',
    title_wo: 'Poids Or Akan',
    description_fr: 'Petit poids en laiton utilisé par les Akan pour peser la poudre d\'or. Ces objets combinent fonction pratique et symbolisme. Chaque forme représente un proverbe ou une valeur culturelle. Ils témoignent de la sophistication du commerce de l\'or en Afrique de l\'Ouest.',
    description_en: 'Small brass weight used by the Akan to weigh gold dust. These objects combine practical function and symbolism. Each shape represents a proverb or cultural value. They testify to the sophistication of the gold trade in West Africa.',
    description_wo: 'Petit poids bu laiton utilisé par Akan ngir peser poudre d\'or. Objets yi combinent fonction pratique ak symbolisme. Chaque forme représente proverbe walla valeur culturelle. Dañu témoigner sophistication bu commerce d\'or ci Afrique de l\'Ouest.',
    historical_context_fr: 'Les Akan du Ghana et de Côte d\'Ivoire ont développé un système complexe de poids pour le commerce de l\'or du 15ème au 20ème siècle. Chaque poids illustre un proverbe, créant ainsi un système de communication visuelle unique qui préserve la sagesse traditionnelle.',
    historical_context_en: 'The Akan of Ghana and Côte d\'Ivoire developed a complex system of weights for gold trade from the 15th to 20th century. Each weight illustrates a proverb, creating a unique visual communication system that preserves traditional wisdom.',
    historical_context_wo: 'Akan yi ci Ghana ak Côte d\'Ivoire développer système complexe bu poids pour commerce d\'or ci 15ème jusque 20ème siècle. Chaque poids illustre proverbe, créant système bu communication visuelle unique bu préserver sagesse traditionnelle.',
    image_url: 'https://art-africain-traditionnel.com/9861-large_default/poids-a-peser-l-or-akan.jpg',
    audio_fr_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    audio_en_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    audio_wo_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    pdf_url: 'https://www.africau.edu/images/default/sample.pdf',
    period: '17ème-19ème siècle',
    origin: 'Ghana, Côte d\'Ivoire',
    materials: 'Laiton',
    artist: 'Artisan Akan',
    created_at: new Date().toISOString()
  },
  {
    id: '6',
    qr_code: 'ART014',
    title_fr: 'Sculpture Nommo Dogon',
    title_en: 'Dogon Nommo Sculpture',
    title_wo: 'Sculpture Nommo Dogon',
    description_fr: 'Figure mythologique des Nommo, êtres amphibiens dans la cosmologie Dogon. Selon la tradition, ils apportèrent la connaissance du ciel aux humains. Cette sculpture illustre la complexité de la pensée cosmologique dogon et leur vision de l\'univers.',
    description_en: 'Mythological figure of the Nommo, amphibian beings in Dogon cosmology. According to tradition, they brought knowledge of the sky to humans. This sculpture illustrates the complexity of Dogon cosmological thought and their vision of the universe.',
    description_wo: 'Figure mythologique bu Nommo, êtres amphibiens ci cosmologie Dogon. Selon tradition, dañu yobbal connaissance bu ciel ci humains. Sculpture bi illustre complexité bu pensée cosmologique dogon ak vision bu univers.',
    historical_context_fr: 'Dans la mythologie Dogon, les Nommo sont des êtres célestes qui auraient visité la Terre dans un vaisseau tournoyant. Ils enseignèrent aux Dogons l\'astronomie, notamment les connaissances sur l\'étoile Sirius B, découverte par les astronomes modernes seulement en 1862.',
    historical_context_en: 'In Dogon mythology, the Nommo are celestial beings who allegedly visited Earth in a spinning vessel. They taught the Dogon astronomy, particularly knowledge about the star Sirius B, discovered by modern astronomers only in 1862.',
    historical_context_wo: 'Ci mythologie Dogon, Nommo yi nekk êtres célestes bu visiter Terre ci vaisseau tournoyant. Dañu teach Dogons yi astronomie, particulièrement xam-xam ci étoile Sirius B, découvert par astronomes modernes ci 1862 rek.',
    image_url: 'https://assets.catawiki.com/image/pr:cw_ldp_l/plain/assets/catawiki/assets/2024/1/23/4/8/0/480612ff-9be2-4f58-b11a-d38a9dbeb491.jpg',
    audio_fr_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    audio_en_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    audio_wo_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    pdf_url: 'https://www.africau.edu/images/default/sample.pdf',
    period: '14ème-16ème siècle',
    origin: 'Mali, Falaise de Bandiagara',
    materials: 'Bois, fer',
    artist: 'Sculpteur Dogon',
    created_at: new Date().toISOString()
  },
  {
    id: '7',
    qr_code: 'ART015',
    title_fr: 'Masque Bwa',
    title_en: 'Bwa Mask',
    title_wo: 'Masque Bwa',
    description_fr: 'Masque planche Bwa du Burkina Faso. Ces masques impressionnants peuvent mesurer jusqu\'à 2 mètres de haut. Les motifs géométriques représentent des symboles cosmologiques. Utilisés lors des initiations et des cérémonies de purification du village.',
    description_en: 'Bwa plank mask from Burkina Faso. These impressive masks can measure up to 2 meters high. Geometric patterns represent cosmological symbols. Used during initiations and village purification ceremonies.',
    description_wo: 'Masque planche Bwa ci Burkina Faso. Masques yi impressionnants mën na mesure jusque 2 mètres. Motifs géométriques représentent symboles cosmologiques. Utilisé ci initiations ak cérémonies bu purification bu village.',
    historical_context_fr: 'Les Bwa du Burkina Faso et du Mali utilisent ces masques lors de cérémonies importantes qui rythment la vie du village. Chaque famille possède ses propres masques transmis de génération en génération. Les danseurs doivent suivre une formation rigoureuse avant de pouvoir les porter.',
    historical_context_en: 'The Bwa of Burkina Faso and Mali use these masks during important ceremonies that punctuate village life. Each family owns its own masks passed down through generations. Dancers must undergo rigorous training before being allowed to wear them.',
    historical_context_wo: 'Bwa yi ci Burkina Faso ak Mali utilisent masques yii ci cérémonies importantes bu rythmer vie bu village. Chaque famille amna masques transmis ci génération ci génération. Danseurs yi des na suivre formation rigoureuse avant mën na porter.',
    image_url: 'https://i.pinimg.com/originals/a5/03/76/a50376eab0694580d04edf68796ac1c7.jpg',
    audio_fr_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    audio_en_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    audio_wo_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    pdf_url: 'https://www.africau.edu/images/default/sample.pdf',
    period: '19ème-20ème siècle',
    origin: 'Burkina Faso, Mali',
    materials: 'Bois, fibres végétales, pigments',
    artist: 'Artisan Bwa',
    created_at: new Date().toISOString()
  },
  {
    id: '8',
    qr_code: 'ART016',
    title_fr: 'Tabouret Ashanti',
    title_en: 'Ashanti Stool',
    title_wo: 'Tabouret Ashanti',
    description_fr: 'Tabouret royal Ashanti du Ghana. Plus qu\'un simple siège, il représente l\'âme de la nation. Le célèbre "Tabouret d\'Or" est le symbole ultime du pouvoir Ashanti. Chaque chef possède son propre tabouret considéré comme sacré.',
    description_en: 'Royal Ashanti stool from Ghana. More than just a seat, it represents the soul of the nation. The famous "Golden Stool" is the ultimate symbol of Ashanti power. Each chief owns their own stool considered sacred.',
    description_wo: 'Tabouret royal Ashanti ci Ghana. Gën ci siège rek, représente âme bu nation bi. "Tabouret d\'Or" famous nekk symbole ultime bu pouvoir Ashanti. Chaque chef amna tabouret considéré comme sacré.',
    historical_context_fr: 'Selon la légende, le Tabouret d\'Or serait descendu du ciel en 1701 pour se poser sur les genoux du roi Osei Tutu, fondateur de l\'Empire Ashanti. Il n\'a jamais touché le sol et représente l\'unité et l\'identité du peuple Ashanti. Les guerres coloniales britanniques visaient en partie sa capture.',
    historical_context_en: 'According to legend, the Golden Stool descended from heaven in 1701 to rest on the lap of King Osei Tutu, founder of the Ashanti Empire. It has never touched the ground and represents the unity and identity of the Ashanti people. British colonial wars partly aimed at its capture.',
    historical_context_wo: 'Selon légende, Tabouret d\'Or bi descendre ci ciel ci 1701 ngir poser ci genoux bu roi Osei Tutu, fondateur bu Empire Ashanti. Jamais la toucher sol te représente unité ak identité bu peuple Ashanti. Guerres coloniales britanniques visaient en partie capture.',
    image_url: 'https://www.africouleur.com/wp-content/uploads/2017/05/tabouret-ashanti-du-ghana-05.jpg',
    audio_fr_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    audio_en_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    audio_wo_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    pdf_url: 'https://www.africau.edu/images/default/sample.pdf',
    period: '18ème-19ème siècle',
    origin: 'Ghana, Empire Ashanti',
    materials: 'Bois précieux, or',
    artist: 'Artisan Royal Ashanti',
    created_at: new Date().toISOString()
  },
  {
    id: '9',
    qr_code: 'ART017',
    title_fr: 'Textile Kente',
    title_en: 'Kente Cloth',
    title_wo: 'Textile Kente',
    description_fr: 'Tissu Kente, textile royal Ashanti aux motifs colorés et complexes. Chaque couleur et motif a une signification symbolique. Traditionnellement tissé à la main sur des métiers étroits, puis assemblé en bandes. Réservé autrefois à la royauté, il est devenu un symbole de fierté africaine.',
    description_en: 'Kente cloth, royal Ashanti textile with colorful and complex patterns. Each color and pattern has symbolic meaning. Traditionally hand-woven on narrow looms, then assembled in strips. Once reserved for royalty, it has become a symbol of African pride.',
    description_wo: 'Textile Kente, textile royal Ashanti ak motifs colorés ak complexes. Chaque couleur ak motif amna signification symbolique. Traditionnellement tissé à main ci métiers étroits, puis assemblé ci bandes. Réservé ci royauté, nekk symbole bu fierté africaine.',
    historical_context_fr: 'Le Kente est né au 17ème siècle dans le royaume Ashanti. Son nom vient du mot "kenten" qui signifie "panier" en référence à son tissage. Il existe plus de 300 motifs différents, chacun portant un nom et une histoire. Le Kente a été popularisé internationalement par des figures comme Nelson Mandela.',
    historical_context_en: 'Kente originated in the 17th century in the Ashanti kingdom. Its name comes from the word "kenten" meaning "basket" in reference to its weaving. There are over 300 different patterns, each bearing a name and story. Kente was popularized internationally by figures like Nelson Mandela.',
    historical_context_wo: 'Kente né ci 17ème siècle ci royaume Ashanti. Nom bi dellusi ci mot "kenten" bu mel "panier" ci référence ci tissage. Amna gën 300 motifs différents, chaque la amna nom ak histoire. Kente popularisé internationalement par figures comme Nelson Mandela.',
    image_url: 'https://d17a17kld06uk8.cloudfront.net/products/147T8UD/96IKL2JS-original.jpg',
    audio_fr_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    audio_en_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    audio_wo_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    pdf_url: 'https://www.africau.edu/images/default/sample.pdf',
    period: '17ème siècle - présent',
    origin: 'Ghana, Royaume Ashanti',
    materials: 'Soie, coton',
    artist: 'Tisserands Ashanti',
    created_at: new Date().toISOString()
  },
  {
    id: '10',
    qr_code: 'ART018',
    title_fr: 'Tête en Terre Cuite de Nok',
    title_en: 'Nok Terracotta Head',
    title_wo: 'Tête Terre Cuite Nok',
    description_fr: 'Tête sculptée en terre cuite de la civilisation Nok du Nigeria. Ces sculptures sont parmi les plus anciennes d\'Afrique subsaharienne, datant de 500 av. J.-C. à 200 apr. J.-C. Elles témoignent d\'une maîtrise artistique remarquable et d\'une société complexe.',
    description_en: 'Terracotta head sculpted by the Nok civilization of Nigeria. These sculptures are among the oldest in sub-Saharan Africa, dating from 500 BC to 200 AD. They testify to remarkable artistic mastery and a complex society.',
    description_wo: 'Tête sculptée ci terre cuite bu civilisation Nok ci Nigeria. Sculptures yi nekk ci gëna ancien ci Afrique subsaharienne, datant 500 av. J.-C. jusque 200 apr. J.-C. Dañu témoigner maîtrise artistique remarquable ak société complexe.',
    historical_context_fr: 'La civilisation Nok est considérée comme l\'une des premières à maîtriser la métallurgie du fer en Afrique de l\'Ouest. Leurs sculptures en terre cuite, découvertes accidentellement dans des mines d\'étain, révèlent une société sophistiquée avec une expression artistique unique. Le style Nok a influencé l\'art africain ultérieur.',
    historical_context_en: 'The Nok civilization is considered one of the first to master iron metallurgy in West Africa. Their terracotta sculptures, accidentally discovered in tin mines, reveal a sophisticated society with unique artistic expression. The Nok style influenced subsequent African art.',
    historical_context_wo: 'Civilisation Nok considérée comme première bu maîtriser métallurgie bu fer ci Afrique de l\'Ouest. Sculptures yi ci terre cuite, découvertes accidentellement ci mines d\'étain, révèlent société sophistiquée ak expression artistique unique. Style Nok influencer art africain ultérieur.',
    image_url: 'https://c8.alamy.com/compfr/2af8t5r/l-art-africain-tete-en-terre-cuite-600-bc-ad-250-cote-de-guinee-du-nigeria-de-la-region-de-nok-2af8t5r.jpg',
    audio_fr_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    audio_en_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    audio_wo_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    pdf_url: 'https://www.africau.edu/images/default/sample.pdf',
    period: '500 av. J.-C. - 200 apr. J.-C.',
    origin: 'Nigeria, Civilisation Nok',
    materials: 'Terre cuite',
    artist: 'Artisan Nok',
    created_at: new Date().toISOString()
  },
  {
    id: '11',
    qr_code: 'ART019',
    title_fr: 'Masque Punu',
    title_en: 'Punu Mask',
    title_wo: 'Masque Punu',
    description_fr: 'Masque blanc Punu du Gabon, représentant un idéal de beauté féminine. Ces masques, appelés "Okuyi", sont utilisés lors de cérémonies funéraires et de divertissement. Le visage blanc symbolise le monde des esprits, tandis que la coiffure élaborée reflète les styles traditionnels.',
    description_en: 'White Punu mask from Gabon, representing an ideal of feminine beauty. These masks, called "Okuyi", are used during funeral ceremonies and entertainment. The white face symbolizes the spirit world, while the elaborate hairstyle reflects traditional styles.',
    description_wo: 'Masque blanc Punu ci Gabon, représentant idéal bu beauté féminine. Masques yi, "Okuyi", utilisé ci cérémonies funéraires ak divertissement. Visage blanc symbolise monde bu esprits, coiffure élaborée reflète styles traditionnels.',
    historical_context_fr: 'Les Punu du Gabon sont réputés pour leurs magnifiques masques blancs. Le danseur portant le masque se déplace sur des échasses, ajoutant une dimension spectaculaire à la performance. Ces masques incarnent l\'esprit d\'une jeune femme décédée revenue pour les festivités.',
    historical_context_en: 'The Punu of Gabon are renowned for their magnificent white masks. The dancer wearing the mask moves on stilts, adding a spectacular dimension to the performance. These masks embody the spirit of a deceased young woman returned for festivities.',
    historical_context_wo: 'Punu yi ci Gabon réputés pour masques blancs magnifiques. Danseur bu porter masque déplace ci échasses, ajoutant dimension spectaculaire ci performance. Masques yi incarnent esprit bu jeune femme décédée bu revenir pour festivités.',
    image_url: 'https://i.pinimg.com/originals/99/7c/78/997c784ea0d20b31fde97d589b4d309c.jpg',
    audio_fr_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    audio_en_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    audio_wo_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    pdf_url: 'https://www.africau.edu/images/default/sample.pdf',
    period: '19ème-20ème siècle',
    origin: 'Gabon, Peuple Punu',
    materials: 'Bois, kaolin, pigments',
    artist: 'Sculpteur Punu',
    created_at: new Date().toISOString()
  },
  {
    id: '12',
    qr_code: 'ART020',
    title_fr: 'Statue Chi Wara',
    title_en: 'Chi Wara Statue',
    title_wo: 'Statue Chi Wara',
    description_fr: 'Cimier Chi Wara des Bambara du Mali. Représente une antilope mythique qui aurait enseigné l\'agriculture aux humains. Porté lors des cérémonies agraires pour honorer le travail de la terre. Symbole de fertilité, de force et de grâce.',
    description_en: 'Chi Wara crest of the Bambara of Mali. Represents a mythical antelope that allegedly taught agriculture to humans. Worn during agricultural ceremonies to honor working the land. Symbol of fertility, strength and grace.',
    description_wo: 'Cimier Chi Wara bu Bambara ci Mali. Représente antilope mythique bu teach agriculture ci humains. Porté ci cérémonies agraires ngir honorer travail bu terre. Symbole bu fertilité, force ak grâce.',
    historical_context_fr: 'Chi Wara signifie "bête de la ferme" en bambara. Ces sculptures représentent souvent un couple d\'antilopes, mâle et femelle, symbolisant l\'équilibre et la complémentarité dans le travail agricole. Les danseurs portent ces cimiers lors de compétitions amicales entre villages pour célébrer les meilleurs agriculteurs.',
    historical_context_en: 'Chi Wara means "farm beast" in Bambara. These sculptures often represent a pair of antelopes, male and female, symbolizing balance and complementarity in agricultural work. Dancers wear these crests during friendly competitions between villages to celebrate the best farmers.',
    historical_context_wo: 'Chi Wara mel "farm beast" ci bambara. Sculptures yi souvent représentent couple d\'antilopes, mâle ak femelle, symbolisant équilibre ak complémentarité ci travail agricole. Danseurs yi portent cimiers yii ci compétitions amicales entre villages ngir célébrer meilleurs agriculteurs.',
    image_url: 'https://i.pinimg.com/236x/ab/a1/10/aba110d0423fbb0161a133485f752425--african-art-masks-african-art-decor.jpg',
    audio_fr_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    audio_en_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    audio_wo_url: 'https://actions.google.com/sounds/v1/ambiences/museum_room_tone.ogg',
    video_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    pdf_url: 'https://www.africau.edu/images/default/sample.pdf',
    period: '19ème-20ème siècle',
    origin: 'Mali, Peuple Bambara',
    materials: 'Bois, métal, fibres',
    artist: 'Artisan Bambara',
    created_at: new Date().toISOString()
  }
];

export function getArtworkByQRCode(qrCode: string): Artwork | undefined {
  return mockArtworks.find(artwork => artwork.qr_code.toUpperCase() === qrCode.toUpperCase());
}

export function getAllArtworks(): Artwork[] {
  return mockArtworks;
}
